name: ESLint

on:
    push:
        branches: [master]
    pull_request:
        # The branches below must be a subset of the branches above
        branches: [master]
    schedule:
        - cron: '27 20 * * 2'

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: 'Checkout Repository'
              uses: actions/checkout@v3

            - name: 'Setup Node.js'
              uses: actions/setup-node@v2
              with:
                  node-version: '14'

            - name: 'Install Dependencies'
              run: yarn install --frozen-lockfile --non-interactive

            - name: 'Lint with ESLint'
              run: yarn run eslint --ext .ts,.tsx --max-warnings 0 .

            - name: 'Lint with Prettier'
              run: yarn run prettier --check .
