name: Manual Lint

jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 12.x

            - name: Install dependencies
              run: yarn install --frozen-lockfile --check-files --non-interactive

            - name: Lint with ESLint
              run: yarn run eslint --ext .ts,.tsx --max-warnings 0 .

            - name: Lint with Prettier
              run: yarn run prettier --check .